#24331A05E3
#To implement read(), readline(), readlines(), write(), writelines() methods on files.
file=open("file.txt","w")
file.write("hello world \n")
file.close()
file=open("file.txt","a")
file.writelines(["hi i am aditya \n","how are you? \n"])
file.close()
file=open("file.txt","r")
print("using read()\n")
print(file.read())
file.close()
file=open("file.txt","r")
print("using readline()\n")
print(file.readline(8))
file.close()
file=open("file.txt","r")
print("using readlines()\n")
print(file.readlines())
file.close()
